title: "opsie.dev"
email: "contact@opsie.dev"
description: "TBD"
url: "https://blog.opsie.dev"
github_username: "opsie-dev"
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed
  
collections:
  posts:
    output: false

meta:
  defaults:
    description: "TBD"
    image: "TBD"
    title: "TBD"
    type: "article"

socials:
  facebook: ""
  linkedin: ""
  x: "@opsie.dev"