exclude:
  - Gemfile
  - Gemfile.lock
  - opsie.gemspec

markdown      : kramdown
highlighter   : rouge
permalink     : date
paginate      : 2
paginate_path : /posts/:num

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir   : _sass
  style      : compressed
