email: "contact@opsie.dev"
description: "TBD"
theme: opsie
title: "opsie.dev | OPS is easy"
url: "https://blog.opsie.dev"

collections:
  posts:
    output: false

meta:
  defaults:
    description: ""
    image: ""
    title: "opsie.dev | OPS is easy"
    type: "article"